[package]
name = "floatviz"
version = "0.1.0"
edition = "2021"
description = "A float visualizer."

[dependencies]
bitvec = "1.0.1"
thiserror = "2.0.8"
num-bigint = "0.4.6"
clap = { version = "4.5.23", features = ["derive"] }